# Generated by Django 5.1.5 on 2025-01-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_description_task_due_date_task_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='Empty value', max_length=100),
            preserve_default=False,
        ),
    ]
